name: 'Prepare Build Dir'
description: 'Prepare the build dir folder for the current job'
inputs:
  build_dir_name:
    description: 'name of the build_dir'
    required: false
    default: 'build-dir'
runs:
  using: "composite"
  steps:
    - name: Getting build dir
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.build_dir_name }}
    - name: Extracting build content
      shell: bash
      run: unzip -o build.zip
    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew