
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
    id 'com.google.dagger.hilt.android'
}

android {
    compileSdk 34

    // Max Version = Max Integer = 214_748_3647
    def versionMajor = 1 // Limit: 213 - Avoid 214 to not affect minor and patch max versions
    def versionMinor = 1 // Limit: 999
    def versionPatch = 0 // Limit: 9999

    defaultConfig {
        applicationId "br.com.davidmag.bingewatcher"
        minSdkVersion 28

        targetSdkVersion 34
        versionCode versionMajor*10000000 + versionMinor*10000 + versionPatch
        versionName "$versionMajor.$versionMinor.$versionPatch"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "BASE_API_URL", "\"https://api.tvmaze.com/\""
        buildConfigField "Long", "NETWORK_TIMEOUT", "${5*60}L"
    }

    buildTypes {
        debug {
            versionNameSuffix "-DEBUG"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
        buildConfig true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.2"
    }
    namespace 'br.com.davidmag.bingewatcher.app'
}

dependencies {

    //KOTLIN
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation "androidx.compose.material3:material3:1.3.0"
    implementation 'androidx.compose.material3:material3-android:1.3.0'
    implementation 'androidx.compose.ui:ui-text-google-fonts:1.7.2'
    implementation 'androidx.compose.ui:ui-tooling-preview-android:1.7.2'
    debugImplementation 'androidx.compose.ui:ui-tooling:1.7.2'
    ksp "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.5.0"

    //COROUTINES AND COMPOSE
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.8.6"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.6"
    implementation 'androidx.navigation:navigation-compose:2.8.1'

    //TIMBER (Logging and Monitoring)
    implementation 'com.jakewharton.timber:timber:4.7.1'

    //STETHO (Monitoring lib)
    def stethoVer = '1.5.1'
    implementation "com.facebook.stetho:stetho:$stethoVer"
    implementation "com.facebook.stetho:stetho-okhttp3:$stethoVer"

    //PAGING
    def paging_version = "3.3.2"
    implementation "androidx.paging:paging-runtime-ktx:$paging_version"
    implementation "androidx.paging:paging-compose:$paging_version"

    //OKHTTP3
    def okhttp3Ver = '4.3.1'
    implementation "com.squareup.okhttp3:okhttp:$okhttp3Ver"
    implementation "com.squareup.okhttp3:logging-interceptor:$okhttp3Ver"

    //RETROFIT
    def retrofitVer = '2.6.1'
    implementation "com.squareup.retrofit2:retrofit:$retrofitVer"
    implementation "com.squareup.retrofit2:converter-gson:$retrofitVer"

    //ROOM (SQLite ORM)
    def roomVer = "2.6.1"
    annotationProcessor "androidx.room:room-compiler:$roomVer"
    implementation "androidx.room:room-runtime:$roomVer"
    implementation "androidx.room:room-common:$roomVer"
    implementation "androidx.room:room-paging:$roomVer"
    implementation "androidx.room:room-ktx:$roomVer"
    ksp "androidx.room:room-compiler:$roomVer"

    //GLIDE
    def glideVer = "4.11.0"
    implementation "com.github.bumptech.glide:glide:4.16.0"
    implementation "com.github.bumptech.glide:compose:1.0.0-beta01"
    implementation ("com.github.bumptech.glide:okhttp3-integration:$glideVer") {
        exclude group: 'glide-parent'
    }
    ksp "com.github.bumptech.glide:compiler:$glideVer"

    //FACEBOOK SHIMMER
    implementation 'com.facebook.shimmer:shimmer:0.5.0'

    //DAGGER2
    def daggerVer = "2.49"
    implementation "com.google.dagger:dagger:$daggerVer"
    implementation "com.google.dagger:dagger-android:$daggerVer"
    implementation "com.google.dagger:dagger-android-support:$daggerVer"
    ksp "com.google.dagger:dagger-compiler:$daggerVer"
    ksp "com.google.dagger:dagger-android-processor:$daggerVer"
    ksp "com.google.dagger:hilt-compiler:$daggerVer"

    // HILT
    def hiltVersion = "2.51"
    implementation("com.google.dagger:hilt-android:$hiltVersion")
    implementation 'androidx.hilt:hilt-navigation-compose:1.2.0'
    ksp("com.google.dagger:hilt-android-compiler:$hiltVersion")
    ksp("com.google.dagger:hilt-compiler:$hiltVersion")

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}