name: Android CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Compacting build result
        run: zip -r build.zip .
      - name: Uploading build dir
        uses: actions/upload-artifact@v2
        with:
          name: build-dir_${CIRCLE_WORKFLOW_ID}
          path: build.zip
          retention-days: 1
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Getting build dir
        uses: actions/download-artifact@v2
        with:
          name: build-dir_${CIRCLE_WORKFLOW_ID}
      - name: Extracting build content
        run: unzip build.zip
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
