name: Android CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Compacting build result
        run: zip -r build.zip .
      - name: Uploading build dir
        uses: actions/upload-artifact@v2
        with:
          name: build-dir
          path: build.zip
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Getting build dir
        uses: actions/download-artifact@v2
        with:
          name: build-dir
      - name: Extracting build content
        run: unzip build.zip
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
