name: Android CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Persist to workspace
        persist_to_workspace:
          root: .
          path:
            - .
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - attach_workspace:
        at: .
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
  generate-artifact:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Compacting build workspace into zip
        run: zip -r build.zip .
      - name: Uploading build dir
        uses: actions/upload-artifact@v2
        with:
          name: build-dir
          path: build.zip
          retention-days: 1
