name: Android CI
on:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --exclude-task test --exclude-task lint
      - name: Compacting build result
        run: zip -r build.zip .
      - name: Uploading build dir
        uses: actions/upload-artifact@v2
        with:
          name: build-dir
          path: build.zip
          retention-days: 1
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build dir
        uses: ./action_download_build_dir
      - name: Run Lint
        run: ./gradlew lint
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build dir
        uses: ./action_download_build_dir
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
  upload-to-marketplace:
    needs: [lint,unit-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Download build dir
        uses: ./action_download_build_dir
      - name: Build Release Bundle
        run: ./gradlew bundleRelease --stacktrace
      - name: Upload release bundle to marketplace
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }} #need to be created
          packageName: br.com.davidmag.bingewatcher
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: production
          inAppUpdatePriority: 2
          userFraction: 0.1
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt

