name: main_ci
on: [push]
runs-on: ubuntu-latest
jobs:
  build:
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
  test:
    steps:
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace