name: Android CI
on:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --stacktrace --exclude-task test --exclude-task lint
      - name: Compacting build result
        run: zip -r build.zip .
      - name: Uploading build dir
        uses: actions/upload-artifact@v2
        with:
          name: build-dir
          path: build.zip
          retention-days: 1
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build dir
        uses: ./action_download_build_dir
      - name: Run Lint
        run: ./gradlew --no-daemon lint
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build dir
        uses: ./action_download_build_dir
      - name: Run Unit Tests
        run: ./gradlew test --no-daemon --stacktrace
  upload-to-marketplace:
    needs: [lint,unit-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Download build dir
        uses: ./action_download_build_dir
      - name: Build release bundle
        run: ./gradlew --no-daemon bundleRelease --stacktrace
      - name: Create keystore
        run: |
          echo "${{ secrets.KEYSTORE_CONTENT }}" >> keystore.jks.b64
          base64 -d -i keystore.jks.b64 > keystore.jks
          rm -f keystore.jks.b64
      - name: Sign the release bundle
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore keystore.jks \
          -storepass ${{ secrets.KEYSTORE_PASS }} -keypass ${{ secrets.KEYSTORE_KEY_PASS }} \
          app/build/outputs/bundle/release/app-release.aab ${{ secrets.KEYSTORE_ALIAS }}
          rm -f keystore.jks
      - name: Upload release bundle to marketplace
        uses: davidmagalhaes/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: br.com.davidmag.bingewatcher
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: production
          inAppUpdatePriority: 2
          userFraction: 0.1
          status: inProgress
          whatsNewDirectory: distribution/whatsnew


